#!/bin/sh

### --------  SLURM  ----------- ###
#SBATCH --job-name=testJob
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --job-name="hello"
#SBATCH --array=0-10:2
#SBATCH --output="hello_%A_%a_%j.out"
#SBATCH --error="hello_%A_%a_%j.err"
##SBATCH --workdir=$HOME/slurm_tutorial
### -------------------------- ###

# Display all variables set by slurm
env | grep "^SLURM" | sort

$HOME/slurm_tutorial/hello.sh
